### ISSUE TITLE
When closing Podman Desktop - no way to restart OpenShift Local

### ISSUE THREAD

**Issue by slemeur** [crc-org/crc-extension#40] opened 2023-04-06 08:36 UTC
I've closed Podman Desktop.
Now it is showing this:
<img width="1456" alt="Capture d’écran 2023-04-06 à 10 34 55" src="https://user-images.githubusercontent.com/1636769/230321892-aaabcb20-d428-47c6-b7a5-429061a8f596.png">

I have no idea on how I can start it.
The resource page is also shown empty
<img width="1456" alt="Capture d’écran 2023-04-06 à 10 35 59" src="https://user-images.githubusercontent.com/1636769/230322104-dced4a51-02b1-4608-ae37-dc4891126efe.png">

**Comment by evidolob** [comment] 2023-04-06 09:36
@slemeur We not control the resource page, we provide k8s connection lifecycle object(with start, stop, delete functions).
Look like it is a bug in podman-desktop itself, when it implemented in very podman way, and some times, ignore k8s existing api.
I'm going to create a linked issue in podman-desktop.

**Comment by gbraad** [comment] 2023-04-07 07:03
Duplicate of:

  * https://github.com/containers/podman-desktop/issues/1953

**Comment by evidolob** [comment] 2023-04-13 13:09
Now it is possible to start/stop/delete crc instance from resource page:
<img width="1048" alt="Screenshot 2023-04-13 at 16 07 11" src="https://user-images.githubusercontent.com/929743/231768370-ca1d3f4c-4d74-4664-abd0-fbe9bc2e5ba3.png">

**Closed by evidolob** 2023-04-13 13:09 UTC
Labels: bug
