### ISSUE TITLE
Output log is very big when something goes wrong when initializing OSL

### ISSUE THREAD

**Issue by odockal** [crc-org/crc-extension#132] opened 2023-05-23 13:22 UTC
Windows 10, Podman Desktop 1.0.1, crc-extension 1.0.1.
I have probably did not reboot machine after installation of the openshift local. When I try to initialize the OSL I got this very big dialog opened describing the problem, but it is hard to read it and get what the problem is.

![pd-openshiftlocal-error](https://github.com/crc-org/crc-extension/assets/19164299/587b20ec-9cee-402c-8b2d-7cc20cadcfd9)

**Comment by gbraad** [comment] 2023-05-23 13:41
Duplicate of https://github.com/crc-org/crc-extension/issues/127 (statement 9) We are aware of this and need to fix this in the CRC backend.

**Closed by gbraad** 2023-05-23 13:41 UTC
